import type { FastifyInstance, FastifyReply } from 'fastify';
import { authenticate, type AuthenticatedRequest } from '../auth/routes.js';
import { createStream, getStream, listStreams, ResourceNotFoundError, setMonitoring, softDeleteStream, streamDto, updateStream } from './service.js';
import { createStreamSchema, monitoringSchema, updateStreamSchema } from './validation.js';
import { z } from 'zod';

const idSchema = z.string().uuid();
const error = (reply: FastifyReply, statusCode: number, code: string, message: string) => reply.code(statusCode).send({ error: { code, message, details: {}, requestId: reply.request.id } });
const ok = (reply: FastifyReply, data: unknown, statusCode = 200) => reply.code(statusCode).send({ data, meta: { requestId: reply.request.id } });
const parseId = (request: { params: unknown }, reply: FastifyReply) => { const parsed = idSchema.safeParse((request.params as { streamId?: unknown })?.streamId); if (!parsed.success) { error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); return null; } return parsed.data; };
const handle = (reply: FastifyReply, cause: unknown) => cause instanceof ResourceNotFoundError ? error(reply, 404, cause.code, 'Resource not found') : undefined;

export const registerStreamRoutes = async (app: FastifyInstance) => {
  app.post('/api/streams', { preHandler: authenticate }, async (request, reply) => { const parsed = createStreamSchema.safeParse(request.body); if (!parsed.success) return error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); try { return ok(reply, { stream: streamDto(await createStream((request as AuthenticatedRequest).user.id, parsed.data)) }, 201); } catch (cause: any) { if (cause?.constraint === 'streams_active_identity_unique') return error(reply, 409, 'CONFLICT', 'Stream already exists'); request.log.error({ err: cause }, 'stream creation failed'); return error(reply, 500, 'INTERNAL_ERROR', 'Internal server error'); } });
  app.get('/api/streams', { preHandler: authenticate }, async (request, reply) => { const query = request.query as { status?: string; monitoringEnabled?: string }; if (query.status && !['LIVE', 'OFFLINE', 'DEGRADED', 'UNKNOWN', 'DISCONNECTED'].includes(query.status)) return error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); if (query.monitoringEnabled !== undefined && !['true', 'false'].includes(query.monitoringEnabled)) return error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); return ok(reply, { streams: (await listStreams((request as AuthenticatedRequest).user.id, { status: query.status, monitoringEnabled: query.monitoringEnabled === undefined ? undefined : query.monitoringEnabled === 'true' })).map(streamDto) }); });
   app.get('/api/streams/:streamId', { preHandler: authenticate }, async (request, reply) => { const id = parseId(request, reply); if (!id) return; try { const detail = await getStream((request as AuthenticatedRequest).user.id, id); return ok(reply, detail); } catch (cause) { return handle(reply, cause) ?? error(reply, 500, 'INTERNAL_ERROR', 'Internal server error'); } });
  app.patch('/api/streams/:streamId', { preHandler: authenticate }, async (request, reply) => { const id = parseId(request, reply); if (!id) return; const parsed = updateStreamSchema.safeParse(request.body); if (!parsed.success) return error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); try { return ok(reply, { stream: await updateStream((request as AuthenticatedRequest).user.id, id, parsed.data) }); } catch (cause: any) { if (cause?.constraint === 'streams_active_identity_unique') return error(reply, 409, 'CONFLICT', 'Stream already exists'); return handle(reply, cause) ?? error(reply, 500, 'INTERNAL_ERROR', 'Internal server error'); } });
  app.patch('/api/streams/:streamId/monitoring', { preHandler: authenticate }, async (request, reply) => { const id = parseId(request, reply); if (!id) return; const parsed = monitoringSchema.safeParse(request.body); if (!parsed.success) return error(reply, 400, 'VALIDATION_ERROR', 'Invalid request'); try { return ok(reply, { stream: await setMonitoring((request as AuthenticatedRequest).user.id, id, parsed.data.enabled) }); } catch (cause) { return handle(reply, cause) ?? error(reply, 500, 'INTERNAL_ERROR', 'Internal server error'); } });
  app.delete('/api/streams/:streamId', { preHandler: authenticate }, async (request, reply) => { const id = parseId(request, reply); if (!id) return; try { return ok(reply, { stream: await softDeleteStream((request as AuthenticatedRequest).user.id, id) }); } catch (cause) { return handle(reply, cause) ?? error(reply, 500, 'INTERNAL_ERROR', 'Internal server error'); } });
};
